version: "3"

volumes:
  kestra-data:

services:
  kestra:
    image: kestra/kestra:latest
    hostname: localhost
    user: "root"
    ports:
      - "8081:8080"
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
    command: server local